name: careerclub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-85.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^1.0.6
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
