name: careerclub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-85.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^1.0.6
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.18
  carousel_slider: ^4.0.0
  curved_navigation_bar: ^1.0.2
  firebase_storage: ^10.2.7
  shimmer: ^2.0.0
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/
    - images/
    - images/icons/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
